# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 04:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('The_Wall', '0003_auto_20170418_0252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='message_id',
            new_name='message',
        ),
    ]
