# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_Reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='book_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='book_review_text',
            new_name='review_text',
        ),
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.CharField(default='Testfuss', max_length=128),
            preserve_default=False,
        ),
    ]
