# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 17:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Dojo_Secrets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='secret',
            name='userWhoLiked',
            field=models.ManyToManyField(related_name='publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='secret',
            name='userWhoPosted',
        ),
        migrations.AddField(
            model_name='secret',
            name='userWhoPosted',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
